//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewDuraApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewDuraApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Address.
        /// </summary>
        internal static string Add_New_Address {
            get {
                return ResourceManager.GetString("Add_New_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Card.
        /// </summary>
        internal static string Add_New_Card {
            get {
                return ResourceManager.GetString("Add_New_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Stop Location.
        /// </summary>
        internal static string Add_Stop_Location {
            get {
                return ResourceManager.GetString("Add_Stop_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        internal static string Address_2 {
            get {
                return ResourceManager.GetString("Address_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address are mandatory.
        /// </summary>
        internal static string Address_are_mandatory {
            get {
                return ResourceManager.GetString("Address_are_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address removed.
        /// </summary>
        internal static string Address_removed {
            get {
                return ResourceManager.GetString("Address_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * All fields are mandatory..
        /// </summary>
        internal static string All_fields_are_mandatory {
            get {
                return ResourceManager.GetString("All_fields_are_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already an User?.
        /// </summary>
        internal static string Already_an_User {
            get {
                return ResourceManager.GetString("Already_an_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_logout {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout from app ?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_logout_from_app {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_logout_from_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Balance.
        /// </summary>
        internal static string Available_Balance {
            get {
                return ResourceManager.GetString("Available_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Offer.
        /// </summary>
        internal static string Available_Offer {
            get {
                return ResourceManager.GetString("Available_Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available offers.
        /// </summary>
        internal static string Available_offers {
            get {
                return ResourceManager.GetString("Available_offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back &amp; Confirm Order.
        /// </summary>
        internal static string Back_Confirm_Order {
            get {
                return ResourceManager.GetString("Back_Confirm_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Price.
        /// </summary>
        internal static string BasePrice {
            get {
                return ResourceManager.GetString("BasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block :.
        /// </summary>
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Email.
        /// </summary>
        internal static string By_Email {
            get {
                return ResourceManager.GetString("By_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Phone.
        /// </summary>
        internal static string By_Phone {
            get {
                return ResourceManager.GetString("By_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Permission Required.
        /// </summary>
        internal static string Camera_Permission_Required {
            get {
                return ResourceManager.GetString("Camera_Permission_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Sa Paghahatid.
        /// </summary>
        internal static string Cash_On_Delivery {
            get {
                return ResourceManager.GetString("Cash_On_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Status.
        /// </summary>
        internal static string Choose_Status {
            get {
                return ResourceManager.GetString("Choose_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Location.
        /// </summary>
        internal static string ChooseLocation {
            get {
                return ResourceManager.GetString("ChooseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password does not match with password..
        /// </summary>
        internal static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        internal static string Contact_Person {
            get {
                return ResourceManager.GetString("Contact_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person name.
        /// </summary>
        internal static string Contact_person_name {
            get {
                return ResourceManager.GetString("Contact_person_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        internal static string Create_Password {
            get {
                return ResourceManager.GetString("Create_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to cancel ?.
        /// </summary>
        internal static string Do_you_really_want_to_cancel {
            get {
                return ResourceManager.GetString("Do_you_really_want_to_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel your order.
        /// </summary>
        internal static string Do_you_want_to_cancel_your_order {
            get {
                return ResourceManager.GetString("Do_you_want_to_cancel_your_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop off (Final Drop Location)....
        /// </summary>
        internal static string Drop_off_Final_Drop_Location {
            get {
                return ResourceManager.GetString("Drop_off_Final_Drop_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dura eat.
        /// </summary>
        internal static string Dura_eat {
            get {
                return ResourceManager.GetString("Dura_eat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuraDrive - Chat with Admin.
        /// </summary>
        internal static string DuraDrive_Chat_with_Admin {
            get {
                return ResourceManager.GetString("DuraDrive_Chat_with_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner with Dura Eats and reach more customers than ever..
        /// </summary>
        internal static string DuraEatsDesc {
            get {
                return ResourceManager.GetString("DuraEatsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dura Eats.
        /// </summary>
        internal static string DuraEatsHeading {
            get {
                return ResourceManager.GetString("DuraEatsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience the fastest and most affordable everyday goods delivery service only with Dura Express..
        /// </summary>
        internal static string DuraExpressDesc {
            get {
                return ResourceManager.GetString("DuraExpressDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dura_Express.
        /// </summary>
        internal static string DuraExpressHeading {
            get {
                return ResourceManager.GetString("DuraExpressHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with your loyal fan base and be amazed at how we can empower your shop and be on top..
        /// </summary>
        internal static string DuraShopDesc {
            get {
                return ResourceManager.GetString("DuraShopDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dura Shop.
        /// </summary>
        internal static string DuraShopHeading {
            get {
                return ResourceManager.GetString("DuraShopHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dura Shops.
        /// </summary>
        internal static string DuraShops {
            get {
                return ResourceManager.GetString("DuraShops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Photo.
        /// </summary>
        internal static string Edit_Photo {
            get {
                return ResourceManager.GetString("Edit_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address*.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any referral code if you have any.
        /// </summary>
        internal static string Enter_any_referral_code_if_you_have_any {
            get {
                return ResourceManager.GetString("Enter_any_referral_code_if_you_have_any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Promocode.
        /// </summary>
        internal static string Enter_Promocode {
            get {
                return ResourceManager.GetString("Enter_Promocode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the drop-off address information.
        /// </summary>
        internal static string Enter_the_drop_off_address_information {
            get {
                return ResourceManager.GetString("Enter_the_drop_off_address_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the otp.
        /// </summary>
        internal static string Enter_the_otp {
            get {
                return ResourceManager.GetString("Enter_the_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the OTP we sent on .
        /// </summary>
        internal static string Enter_the_OTP_we_sent_on {
            get {
                return ResourceManager.GetString("Enter_the_OTP_we_sent_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the pickup address information.
        /// </summary>
        internal static string Enter_the_pickup_address_information {
            get {
                return ResourceManager.GetString("Enter_the_pickup_address_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the reason to cancel this order.
        /// </summary>
        internal static string Enter_the_reason_to_cancel_this_order {
            get {
                return ResourceManager.GetString("Enter_the_reason_to_cancel_this_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Location.
        /// </summary>
        internal static string EnterLocation {
            get {
                return ResourceManager.GetString("EnterLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Pickup.
        /// </summary>
        internal static string EnterPickup {
            get {
                return ResourceManager.GetString("EnterPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on removing address.
        /// </summary>
        internal static string Error_on_removing_address {
            get {
                return ResourceManager.GetString("Error_on_removing_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee breakdown details.
        /// </summary>
        internal static string Fee_breakdown_details {
            get {
                return ResourceManager.GetString("Fee_breakdown_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name*.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get OTP on Email.
        /// </summary>
        internal static string Get_OTP_on_Email {
            get {
                return ResourceManager.GetString("Get_OTP_on_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get OTP on Phone.
        /// </summary>
        internal static string Get_OTP_on_Phone {
            get {
                return ResourceManager.GetString("Get_OTP_on_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get OTP.
        /// </summary>
        internal static string GetOTP {
            get {
                return ResourceManager.GetString("GetOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        internal static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give Permission.
        /// </summary>
        internal static string GivePermission {
            get {
                return ResourceManager.GetString("GivePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google map is not able to pick address currently , try again after some time..
        /// </summary>
        internal static string Google_map_is_not_able_to_pick_address_currently {
            get {
                return ResourceManager.GetString("Google_map_is_not_able_to_pick_address_currently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Center.
        /// </summary>
        internal static string Help_Center {
            get {
                return ResourceManager.GetString("Help_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, my name is.
        /// </summary>
        internal static string Hi_my_name_is {
            get {
                return ResourceManager.GetString("Hi_my_name_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Accept the .
        /// </summary>
        internal static string I_Accept {
            get {
                return ResourceManager.GetString("I_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name*.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        internal static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        internal static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login With Email.
        /// </summary>
        internal static string LoginWithEmail {
            get {
                return ResourceManager.GetString("LoginWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login With Phone Number.
        /// </summary>
        internal static string LoginWithPhoneNumber {
            get {
                return ResourceManager.GetString("LoginWithPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Read.
        /// </summary>
        internal static string Mark_as_Read {
            get {
                return ResourceManager.GetString("Mark_as_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max length 100.
        /// </summary>
        internal static string max_length_100 {
            get {
                return ResourceManager.GetString("max_length_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        internal static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Address.
        /// </summary>
        internal static string My_Address {
            get {
                return ResourceManager.GetString("My_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Orders.
        /// </summary>
        internal static string My_Orders {
            get {
                return ResourceManager.GetString("My_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string My_Profile {
            get {
                return ResourceManager.GetString("My_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Saved Address.
        /// </summary>
        internal static string My_Saved_Address {
            get {
                return ResourceManager.GetString("My_Saved_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New here ?.
        /// </summary>
        internal static string Newhere {
            get {
                return ResourceManager.GetString("Newhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Address save to show.
        /// </summary>
        internal static string No_Address_saved_to_show {
            get {
                return ResourceManager.GetString("No_Address_saved_to_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Notifications data.
        /// </summary>
        internal static string No_Notifications_data {
            get {
                return ResourceManager.GetString("No_Notifications_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No offers available.
        /// </summary>
        internal static string No_offers_available {
            get {
                return ResourceManager.GetString("No_offers_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No promo code available.
        /// </summary>
        internal static string No_promo_code_available {
            get {
                return ResourceManager.GetString("No_promo_code_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.
        /// </summary>
        internal static string No_records_found {
            get {
                return ResourceManager.GetString("No_records_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No services selected.
        /// </summary>
        internal static string No_services_selected {
            get {
                return ResourceManager.GetString("No_services_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check Your Internet Connection..
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        internal static string Not_Connected {
            get {
                return ResourceManager.GetString("Not_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to internet..
        /// </summary>
        internal static string Not_connected_to_internet {
            get {
                return ResourceManager.GetString("Not_connected_to_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer &amp;amp; Promocode apply.
        /// </summary>
        internal static string Offer_Promocode_Apply {
            get {
                return ResourceManager.GetString("Offer_Promocode_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers &amp; Promo.
        /// </summary>
        internal static string Offers_Promo {
            get {
                return ResourceManager.GetString("Offers_Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or Sign in With.
        /// </summary>
        internal static string Or_Sign_in_With {
            get {
                return ResourceManager.GetString("Or_Sign_in_With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number .
        /// </summary>
        internal static string Order_Number {
            get {
                return ResourceManager.GetString("Order_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered on .
        /// </summary>
        internal static string Ordered_on {
            get {
                return ResourceManager.GetString("Ordered_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between 8 to 15 characters, it must also contain atleast 1 lowercase,1 uppercase, 1 special character and 1 digit..
        /// </summary>
        internal static string Password_must_be_between_8_to_15_characters {
            get {
                return ResourceManager.GetString("Password_must_be_between_8_to_15 characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Successfully.
        /// </summary>
        internal static string Password_Reset_Successfully {
            get {
                return ResourceManager.GetString("Password_Reset_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Details.
        /// </summary>
        internal static string PersonalDetails {
            get {
                return ResourceManager.GetString("PersonalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number*.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick from camera.
        /// </summary>
        internal static string Pick_from_camera {
            get {
                return ResourceManager.GetString("Pick_from_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick from gallery.
        /// </summary>
        internal static string Pick_from_gallery {
            get {
                return ResourceManager.GetString("Pick_from_gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup Location.
        /// </summary>
        internal static string Pickup_Location {
            get {
                return ResourceManager.GetString("Pickup_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup Schedule.
        /// </summary>
        internal static string PickupSchedule {
            get {
                return ResourceManager.GetString("PickupSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter address 1.
        /// </summary>
        internal static string Please_enter_address_1 {
            get {
                return ResourceManager.GetString("Please_enter_address_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter address 2.
        /// </summary>
        internal static string Please_enter_address_2 {
            get {
                return ResourceManager.GetString("Please_enter_address_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter contact person name.
        /// </summary>
        internal static string Please_enter_contact_person_name {
            get {
                return ResourceManager.GetString("Please_enter_contact_person_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter minimum 10 digit phone number..
        /// </summary>
        internal static string Please_enter_minimum_10_digit_phone_number {
            get {
                return ResourceManager.GetString("Please_enter_minimum_10_digit_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter promo code to get offer.
        /// </summary>
        internal static string Please_enter_promo_code_to_get_offer {
            get {
                return ResourceManager.GetString("Please_enter_promo_code_to_get_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email id..
        /// </summary>
        internal static string Please_enter_valid_email_id {
            get {
                return ResourceManager.GetString("Please_enter_valid_email_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid first name.
        /// </summary>
        internal static string Please_enter_valid_first_name {
            get {
                return ResourceManager.GetString("Please_enter_valid_first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid last name.
        /// </summary>
        internal static string Please_enter_valid_last_name {
            get {
                return ResourceManager.GetString("Please_enter_valid_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid phone number.
        /// </summary>
        internal static string Please_enter_valid_phone_number {
            get {
                return ResourceManager.GetString("Please_enter_valid_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide rating.
        /// </summary>
        internal static string Please_provide_rating {
            get {
                return ResourceManager.GetString("Please_provide_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select area.
        /// </summary>
        internal static string Please_select_area {
            get {
                return ResourceManager.GetString("Please_select_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select below one.
        /// </summary>
        internal static string Please_select_below_one {
            get {
                return ResourceManager.GetString("Please_select_below_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select profile pic.
        /// </summary>
        internal static string Please_select_profile_pic {
            get {
                return ResourceManager.GetString("Please_select_profile_pic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your country code.
        /// </summary>
        internal static string Please_select_your_country_code {
            get {
                return ResourceManager.GetString("Please_select_your_country_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell us your Mobile number to proceed further..
        /// </summary>
        internal static string Please_tell_us_your_Mobile_number_to_proceed_further {
            get {
                return ResourceManager.GetString("Please_tell_us_your_Mobile_number_to_proceed_further", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell us about yourself and upload a picture..
        /// </summary>
        internal static string Please_upload_a_picture {
            get {
                return ResourceManager.GetString("Please_upload_a_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Breakdown.
        /// </summary>
        internal static string PriceBreakdown {
            get {
                return ResourceManager.GetString("PriceBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate &amp; Review.
        /// </summary>
        internal static string Rate_Review {
            get {
                return ResourceManager.GetString("Rate_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Searched.
        /// </summary>
        internal static string RecentSearched {
            get {
                return ResourceManager.GetString("RecentSearched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refer a Friend.
        /// </summary>
        internal static string Refer_a_Friend {
            get {
                return ResourceManager.GetString("Refer_a_Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refer code does not match.Do you really want to proceed without referal code?.
        /// </summary>
        internal static string Refer_code_does_not_match {
            get {
                return ResourceManager.GetString("Refer_code_does_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Now.
        /// </summary>
        internal static string RegisterNow {
            get {
                return ResourceManager.GetString("RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend OTP.
        /// </summary>
        internal static string ResendOTP {
            get {
                return ResourceManager.GetString("ResendOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Address.
        /// </summary>
        internal static string Saved_Address {
            get {
                return ResourceManager.GetString("Saved_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Addresses.
        /// </summary>
        internal static string Saved_Addresses {
            get {
                return ResourceManager.GetString("Saved_Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Cards.
        /// </summary>
        internal static string Saved_Cards {
            get {
                return ResourceManager.GetString("Saved_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for the driver.
        /// </summary>
        internal static string Search_for_the_driver {
            get {
                return ResourceManager.GetString("Search_for_the_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Restaurant, Dish etc....
        /// </summary>
        internal static string Search_Restaurant {
            get {
                return ResourceManager.GetString("Search_Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Your Location.
        /// </summary>
        internal static string Search_Your_Location {
            get {
                return ResourceManager.GetString("Search_Your_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Payment Mode.
        /// </summary>
        internal static string Select_Payment_Mode {
            get {
                return ResourceManager.GetString("Select_Payment_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status.
        /// </summary>
        internal static string Select_Status {
            get {
                return ResourceManager.GetString("Select_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Vehicle.
        /// </summary>
        internal static string Select_Vehicle {
            get {
                return ResourceManager.GetString("Select_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api response error, please try again.
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service type.
        /// </summary>
        internal static string Service_type {
            get {
                return ResourceManager.GetString("Service_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Type.
        /// </summary>
        internal static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your pickup and drop off location.Dura Express provides best services to deliver your items..
        /// </summary>
        internal static string Set_your_pickup_and_drop_off_location_Dura_Express {
            get {
                return ResourceManager.GetString("Set_your_pickup_and_drop_off_location_Dura_Express", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit &amp; Cancel Order.
        /// </summary>
        internal static string Submit_Cancel_Order {
            get {
                return ResourceManager.GetString("Submit_Cancel_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Chat.
        /// </summary>
        internal static string Support_Chat {
            get {
                return ResourceManager.GetString("Support_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap on map to set your position.
        /// </summary>
        internal static string Tap_on_map_to_set_your_position {
            get {
                return ResourceManager.GetString("Tap_on_map_to_set_your_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Services..
        /// </summary>
        internal static string Terms_of_Services {
            get {
                return ResourceManager.GetString("Terms_of_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for provide the rating.
        /// </summary>
        internal static string Thanks_for_provide_the_rating {
            get {
                return ResourceManager.GetString("Thanks_for_provide_the_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip Amount.
        /// </summary>
        internal static string TipAmount {
            get {
                return ResourceManager.GetString("TipAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token expired, you will be redirected to login.
        /// </summary>
        internal static string Token_expired {
            get {
                return ResourceManager.GetString("Token_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Total distance.
        /// </summary>
        internal static string Total_distance {
            get {
                return ResourceManager.GetString("Total_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Total distance 20 km).
        /// </summary>
        internal static string Total_distance_20_km {
            get {
                return ResourceManager.GetString("Total_distance_20_km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Order.
        /// </summary>
        internal static string Track_Order {
            get {
                return ResourceManager.GetString("Track_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subukang Muli.
        /// </summary>
        internal static string Try_Again {
            get {
                return ResourceManager.GetString("Try_Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type notes to your driver (Optional).
        /// </summary>
        internal static string Type_notes_to_your_driver_Optional {
            get {
                return ResourceManager.GetString("Type_notes_to_your_driver_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your current location.
        /// </summary>
        internal static string Use_current_location {
            get {
                return ResourceManager.GetString("Use_current_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity :.
        /// </summary>
        internal static string Validity {
            get {
                return ResourceManager.GetString("Validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Number.
        /// </summary>
        internal static string VehicleNumber {
            get {
                return ResourceManager.GetString("VehicleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        internal static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        internal static string View_Profile {
            get {
                return ResourceManager.GetString("View_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are Working on it.It is in Progress..
        /// </summary>
        internal static string We_are_Working_on_it_It_is_in_Progress {
            get {
                return ResourceManager.GetString("We_are_Working_on_it_It_is_in_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natagpuan ka namin ng isang Driver.
        /// </summary>
        internal static string We_ve_Found_You_A_Driver {
            get {
                return ResourceManager.GetString("We_ve_Found_You_A_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where To(Final Drop Location).
        /// </summary>
        internal static string Where_To_Final_Drop_Location {
            get {
                return ResourceManager.GetString("Where_To_Final_Drop_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to?.
        /// </summary>
        internal static string Whereto {
            get {
                return ResourceManager.GetString("Whereto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will review later.
        /// </summary>
        internal static string will_review_later {
            get {
                return ResourceManager.GetString("will_review_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakay ka na (nakabinbin ang pag-apruba).
        /// </summary>
        internal static string You_are_now_rider_pending_approval {
            get {
                return ResourceManager.GetString("You_are_now_rider_pending_approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll be have to cash pay P16 to delivery person.
        /// </summary>
        internal static string You_ll_be_have_to_cash_pay_delivery_person {
            get {
                return ResourceManager.GetString("You_ll_be_have_to_cash_pay_delivery_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * You must fill all of the fields..
        /// </summary>
        internal static string You_must_fill_all_of_the_fields {
            get {
                return ResourceManager.GetString("You_must_fill_all_of_the_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email or phone is already registered.
        /// </summary>
        internal static string Your_email_or_phone_is_already_registered {
            get {
                return ResourceManager.GetString("Your_email_or_phone_is_already_registered", resourceCulture);
            }
        } 
        internal static string Location_service_not_enabled
        {
            get {
                return ResourceManager.GetString("Location_service_not_enabled", resourceCulture);
            }
        }
        internal static string Camera_Permission
        {
            get {
                return ResourceManager.GetString("Camera_Permission", resourceCulture);
            }
        }
        internal static string contacts
        {
            get {
                return ResourceManager.GetString("contacts", resourceCulture);
            }
        }
        internal static string locations
        {
            get {
                return ResourceManager.GetString("locations", resourceCulture);
            }
        }
        internal static string Need_to_access_your_camera_so_that_you_can_upload_your_profile_picture_and_other_documents
        {
            get {
                return ResourceManager.GetString("Need_to_access_your_camera_so_that_you_can_upload_your_profile_picture_and_other_documents", resourceCulture);
            }
        }
        internal static string Contact_Permission
        {
            get {
                return ResourceManager.GetString("Contact_Permission", resourceCulture);
            }
        }
        internal static string Location_Permission
        {
            get {
                return ResourceManager.GetString("Location_Permission", resourceCulture);
            }
        }
        internal static string Storage_Permission
        {
            get {
                return ResourceManager.GetString("Storage_Permission", resourceCulture);
            }
        }
        internal static string We_need_to_access_your_phone_book_in_order_to_save_address_with_contact
        {
            get {
                return ResourceManager.GetString("We_need_to_access_your_phone_book_in_order_to_save_address_with_contact", resourceCulture);
            }
        }
        internal static string We_need_to_find_where_you_are_in_order_to_better_facilitate_you
        {
            get {
                return ResourceManager.GetString("We_need_to_find_where_you_are_in_order_to_better_facilitate_you", resourceCulture);
            }
        }
        internal static string Need_to_access_your_gallery_so_that_you_can_easily_upload_your_documents
        {
            get {
                return ResourceManager.GetString("Need_to_access_your_gallery_so_that_you_can_easily_upload_your_documents", resourceCulture);
            }
        }
        internal static string Your_account_is_not_verified
        {
            get {
                return ResourceManager.GetString("Your_account_is_not_verified", resourceCulture);
            }
        }
        internal static string Please_wait
        {
            get {
                return ResourceManager.GetString("Please_wait", resourceCulture);
            }
        }
        internal static string We_are_coming_soon
        {
            get {
                return ResourceManager.GetString("We_are_coming_soon", resourceCulture);
            }
        }
        internal static string Driver_arrived
        {
            get {
                return ResourceManager.GetString("Driver_arrived", resourceCulture);
            }
        }
        internal static string Wallet_Amount_is_less_than_order_amount_Do_you_really_want_to_proceed_with_COD
        {
            get {
                return ResourceManager.GetString("Wallet_Amount_is_less_than_order_amount_Do_you_really_want_to_proceed_with_COD", resourceCulture);
            }
        }
        internal static string will_be_deducted_from_your_wallet_Do_you_really_want_to_proceed
        {
            get {
                return ResourceManager.GetString("will_be_deducted_from_your_wallet_Do_you_really_want_to_proceed", resourceCulture);
            }
        }
        internal static string Searching_Driver
        {
            get {
                return ResourceManager.GetString("Searching_Driver", resourceCulture);
            }
        }
        internal static string Recharge_Now
        {
            get {
                return ResourceManager.GetString("Recharge_Now", resourceCulture);
            }
        }
        internal static string Your_wallet_amount_is_notsufficient_Do_you_want_to_proceed_with_COD
        {
            get {
                return ResourceManager.GetString("Your_wallet_amount_is_notsufficient_Do_you_want_to_proceed_with_COD", resourceCulture);
            }
        }
        internal static string You_will_have_to_pay
        {
            get {
                return ResourceManager.GetString("You_will_have_to_pay", resourceCulture);
            }
        }
        internal static string in_cash_when_delivered
        {
            get {
                return ResourceManager.GetString("in_cash_when_delivered", resourceCulture);
            }
        }
        internal static string Select_an_options
        {
            get {
                return ResourceManager.GetString("Select_an_options", resourceCulture);
            }
        }
        internal static string Connected
        {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        internal static string Already_Exist
        {
            get {
                return ResourceManager.GetString("Already_Exist", resourceCulture);
            }
        }
        internal static string This_phone_number_is_already_registered
        {
            get {
                return ResourceManager.GetString("This_phone_number_is_already_registered", resourceCulture);
            }
        }
        internal static string API_Error
        {
            get {
                return ResourceManager.GetString("API_Error", resourceCulture);
            }
        }
        internal static string Wrong_code
        {
            get {
                return ResourceManager.GetString("Wrong_code", resourceCulture);
            }
        }
        internal static string Your_OTP_is_not_matching_Please_resend_to_get_new_one
        {
            get {
                return ResourceManager.GetString("Your_OTP_is_not_matching_Please_resend_to_get_new_one", resourceCulture);
            }
        }
        internal static string No_driver_location_link_found
        {
            get {
                return ResourceManager.GetString("No_driver_location_link_found", resourceCulture);
            }
        }
        internal static string No_more_record_found
        {
            get {
                return ResourceManager.GetString("No_more_record_found", resourceCulture);
            }
        }
        internal static string Card_Removed
        {
            get {
                return ResourceManager.GetString("Card_Removed", resourceCulture);
            }
        }
        internal static string No_promo_code_offer_available_for_you
        {
            get {
                return ResourceManager.GetString("No_promo_code_offer_available_for_you", resourceCulture);
            }
        }
        internal static string This_promo_will_be_applied_for_your_next_order
        {
            get {
                return ResourceManager.GetString("This_promo_will_be_applied_for_your_next_order", resourceCulture);
            }
        }
        internal static string Please_enter_the_referral_code
        {
            get {
                return ResourceManager.GetString("Please_enter_the_referral_code", resourceCulture);
            }
        }
        internal static string Dura_Drive_ReferralCode
        {
            get {
                return ResourceManager.GetString("Dura_Drive_ReferralCode", resourceCulture);
            }
        }
        internal static string Refer_a_friend_get_you_and_your_friend_off_on_food_ordering
        {
            get {
                return ResourceManager.GetString("Refer_a_friend_get_you_and_your_friend_off_on_food_ordering", resourceCulture);
            }
        }
        internal static string Add
        {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        internal static string Card_Updated
        {
            get {
                return ResourceManager.GetString("Card_Updated", resourceCulture);
            }
        }
        internal static string New_Card_Added
        {
            get {
                return ResourceManager.GetString("New_Card_Added", resourceCulture);
            }
        }
        internal static string Edit_Info
        {
            get {
                return ResourceManager.GetString("Edit_Info", resourceCulture);
            }
        }
        internal static string Location_updated_successfully
        {
            get {
                return ResourceManager.GetString("Location_updated_successfully", resourceCulture);
            }
        }
        internal static string Location_not_updated_Dura_Server_down
        {
            get {
                return ResourceManager.GetString("Location_not_updated_Dura_Server_down", resourceCulture);
            }
        }
        internal static string Phone_number_updated_successfully
        {
            get {
                return ResourceManager.GetString("Phone_number_updated_successfully", resourceCulture);
            }
        }
        internal static string Please_recheck_your_phone_number_It_is_already_present_in_dura_server
        {
            get {
                return ResourceManager.GetString("Please_recheck_your_phone_number_It_is_already_present_in_dura_server", resourceCulture);
            }
        }
        internal static string Edit_Location
        {
            get {
                return ResourceManager.GetString("Edit_Location", resourceCulture);
            }
        }
        internal static string Please_enter_user_full_name
        {
            get {
                return ResourceManager.GetString("Please_enter_user_full_name", resourceCulture);
            }
        }
        internal static string Please_enter_valid_user_name
        {
            get {
                return ResourceManager.GetString("Please_enter_valid_user_name", resourceCulture);
            }
        }
        internal static string Your_UserName_updated_successfully
        {
            get {
                return ResourceManager.GetString("Your_UserName_updated_successfully", resourceCulture);
            }
        }
        internal static string Error_in_updating_records
        {
            get {
                return ResourceManager.GetString("Error_in_updating_records", resourceCulture);
            }
        }
        internal static string Sending_OTP_Server_Error
        {
            get {
                return ResourceManager.GetString("Sending_OTP_Server_Error", resourceCulture);
            }
        }
        internal static string Send_OTP
        {
            get {
                return ResourceManager.GetString("Send_OTP", resourceCulture);
            }
        }
        internal static string Linked
        {
            get {
                return ResourceManager.GetString("Linked", resourceCulture);
            }
        }
        internal static string Not_Linked
        {
            get {
                return ResourceManager.GetString("Not_Linked", resourceCulture);
            }
        }
        internal static string error_on_uploading_image_try_again
        {
            get {
                return ResourceManager.GetString("error_on_uploading_image_try_again", resourceCulture);
            }
        }
        internal static string Id_card_front_image_removed
        {
            get {
                return ResourceManager.GetString("Id_card_front_image_removed", resourceCulture);
            }
        }
        internal static string Id_card_back_image_removed
        {
            get {
                return ResourceManager.GetString("Id_card_back_image_removed", resourceCulture);
            }
        }
        internal static string Driving_license_front_image_removed
        {
            get {
                return ResourceManager.GetString("Driving_license_front_image_removed", resourceCulture);
            }
        }
        internal static string Driving_license_back_image_removed
        {
            get {
                return ResourceManager.GetString("Driving_license_back_image_removed", resourceCulture);
            }
        }
        internal static string Location_not_found
        {
            get {
                return ResourceManager.GetString("Location_not_found", resourceCulture);
            }
        }
        internal static string Please_check_your_Phone_number_It_may_be_not_reachable
        {
            get {
                return ResourceManager.GetString("Please_check_your_Phone_number_It_may_be_not_reachable", resourceCulture);
            }
        }
        internal static string Enter_the_address
        {
            get {
                return ResourceManager.GetString("Enter_the_address", resourceCulture);
            }
        }
        internal static string Enter_your_drop_address
        {
            get {
                return ResourceManager.GetString("Enter_your_drop_address", resourceCulture);
            }
        }
        internal static string Enter_the_stop_address
        {
            get {
                return ResourceManager.GetString("Enter_the_stop_address", resourceCulture);
            }
        }
        internal static string Enter_the_pickup_address
        {
            get {
                return ResourceManager.GetString("Enter_the_pickup_address", resourceCulture);
            }
        }
        internal static string Please_enter_valid_amount
        {
            get {
                return ResourceManager.GetString("Please_enter_valid_amount", resourceCulture);
            }
        }
        internal static string Promo_code_applied_successfully
        {
            get {
                return ResourceManager.GetString("Promo_code_applied_successfully", resourceCulture);
            }
        }
        internal static string Your_order_location_is_not_selected_right_Please_recheck_your_order_confirm_location_pickup_dropup_again
        {
            get {
                return ResourceManager.GetString("Your_order_location_is_not_selected_right_Please_recheck_your_order_confirm_location_pickup_dropup_again", resourceCulture);
            }
        }
        internal static string Please_select_Pickup_Schedule
        {
            get {
                return ResourceManager.GetString("Please_select_Pickup_Schedule", resourceCulture);
            }
        }
        internal static string Please_select_Pickup_location
        {
            get {
                return ResourceManager.GetString("Please_select_Pickup_location", resourceCulture);
            }
        }
        internal static string Please_select_desctination_where_to_Final_Drop_location
        {
            get {
                return ResourceManager.GetString("Please_select_desctination_where_to_Final_Drop_location", resourceCulture);
            }
        }
        internal static string Please_Wait_Finding_Driver
        {
            get {
                return ResourceManager.GetString("Please_Wait_Finding_Driver", resourceCulture);
            }
        }
        internal static string Sorry_we_dont_serve_this_location_yet
        {
            get {
                return ResourceManager.GetString("Sorry_we_dont_serve_this_location_yet", resourceCulture);
            }
        }
        internal static string Our_Service_are_currently_not_available_in_this_city_We_will_notify_you_as_soon_as_we_launch
        {
            get {
                return ResourceManager.GetString("Our_Service_are_currently_not_available_in_this_city_We_will_notify_you_as_soon_as_we_launch", resourceCulture);
            }
        }
        internal static string Track_Dura_Express_Order
        {
            get {
                return ResourceManager.GetString("Track_Dura_Express_Order", resourceCulture);
            }
        }
        internal static string No_Data_Found
        {
            get {
                return ResourceManager.GetString("No_Data_Found", resourceCulture);
            }
        }
        internal static string Pending_OrderNotPickedYet
        {
            get {
                return ResourceManager.GetString("Pending_OrderNotPickedYet", resourceCulture);
            }
        }
        internal static string Ongoing_OrderPicked
        {
            get {
                return ResourceManager.GetString("Ongoing_OrderPicked", resourceCulture);
            }
        }
        internal static string Completed_OrderDelivered
        {
            get {
                return ResourceManager.GetString("Completed_OrderDelivered", resourceCulture);
            }
        }
        internal static string Cancelled_OrderCancelled
        {
            get {
                return ResourceManager.GetString("Cancelled_OrderCancelled", resourceCulture);
            }
        }
        internal static string We_are_working_with_google_for_tracking_link_Backend_Team_work_is_inProgress
        {
            get {
                return ResourceManager.GetString("We_are_working_with_google_for_tracking_link_Backend_Team_work_is_inProgress", resourceCulture);
            }
        }
        internal static string time_should_not_be_less_than_current_time
        {
            get {
                return ResourceManager.GetString("time_should_not_be_less_than_current_time", resourceCulture);
            }
        }
        internal static string You_can_add_maximum_three_stop_location
        {
            get {
                return ResourceManager.GetString("You_can_add_maximum_three_stop_location", resourceCulture);
            }
        }
        internal static string Document_1_front_image_removed
        {
            get {
                return ResourceManager.GetString("Document_1_front_image_removed", resourceCulture);
            }
        }
        internal static string Document_1_back_image_removed
        {
            get {
                return ResourceManager.GetString("Document_1_back_image_removed", resourceCulture);
            }
        }
        internal static string Document_2_front_image_removed
        {
            get {
                return ResourceManager.GetString("Document_2_front_image_removed", resourceCulture);
            }
        }
        internal static string Document_2_back_image_removed
        {
            get {
                return ResourceManager.GetString("Document_2_back_image_removed", resourceCulture);
            }
        }
        internal static string New_Address_Added
        {
            get {
                return ResourceManager.GetString("New_Address_Added", resourceCulture);
            }
        }
        internal static string Address_Updated
        {
            get {
                return ResourceManager.GetString("Address_Updated", resourceCulture);
            }
        }
    }
}
